package main

import (
	_ "github.com/Prompiriya084/go-mq/OrderService/docs" // the docs generated by swag init

	// models "github.com/Prompiriya084/go-mq/Models"

	bootstrap "github.com/Prompiriya084/go-mq/OrderService/Internal/Bootstrap"
	database "github.com/Prompiriya084/go-mq/OrderService/Internal/Infrastructure/Database"
	rabbitMQ "github.com/Prompiriya084/go-mq/OrderService/Internal/Infrastructure/Eventbus"
)

// @title Order Service API
// @version 1.0
// @description API Example
// @BasePath /
// @schemes http
func main() {
	db := database.InitDb()
	ch, err := rabbitMQ.MQConnectionInit()
	if err != nil {
		panic(err.Error())
	}

	// 👇 topology อยู่ตรงนี้
	if err := rabbitMQ.DeclareTopology(ch); err != nil {
		panic(err.Error())
	}

	bootstrap.StartOrderAPI(db, ch)
}
