package main

import (
	"os"

	_ "github.com/Prompiriya084/go-mq/OrderService/docs" // the docs generated by swag init

	eventbus "github.com/Prompiriya084/go-mq/EventBus"

	// models "github.com/Prompiriya084/go-mq/Models"
	adapters_handlers "github.com/Prompiriya084/go-mq/OrderService/Internal/Adapters/Handlers"
	adapters_repositories "github.com/Prompiriya084/go-mq/OrderService/Internal/Adapters/Repositories"
	services "github.com/Prompiriya084/go-mq/OrderService/Internal/Core/Services"
	utilities_validator "github.com/Prompiriya084/go-mq/OrderService/Internal/Core/Utilities/Validator"
	database "github.com/Prompiriya084/go-mq/OrderService/Internal/Infrastructure/Database"
	models "github.com/Prompiriya084/go-mq/OrderService/Models"
	routes "github.com/Prompiriya084/go-mq/OrderService/Web/Routes"
	"github.com/gofiber/contrib/swagger"
	"github.com/gofiber/fiber/v2"
)

// @title Order Service API
// @version 1.0
// @description API Example
// @BasePath /
// @schemes http
func main() {
	app := fiber.New()
	db := database.InitDb()

	// Serve swagger.json
	app.Static("/docs", "./docs")
	// Correct swagger config (must NOT be nil)
	cfg := swagger.Config{
		Title:    "Order Service API",
		Path:     "swagger", // UI root
		FilePath: "./docs/swagger.json",
	}

	// Generate handler (this is where your panic happened)
	swaggerHandler := swagger.New(cfg)
	app.Get("/swagger/*", swaggerHandler)

	mqOrderEventbus := eventbus.NewMQEventbus[models.Order](os.Getenv("RABBITMQ_URL"))
	orderRepo := adapters_repositories.NewOrderRepository(db)
	orderService := services.NewOrderService(orderRepo, mqOrderEventbus)

	validator := utilities_validator.NewValidator()

	orderHandler := adapters_handlers.NewOrderHandler(orderService, validator, mqOrderEventbus)
	routes.OrderSetupRouter(app, orderHandler)

	//For message queue
	go orderHandler.InventoryConfirmed()
	app.Listen(":8080")
}
